import { Status, useContract, useDirectListings } from '@thirdweb-dev/react';
import {
  MUMBAI_DIGITIZE_ETH_ADDRESS,
  MUMBAI_MARKETPLACE_ADDRESS,
} from '../../constant/addresses';
import styles from '../../styles/Home.module.css';
import { PackNFTCard } from '../../components/PackNFT';
import Navbar from '@/components/Navbar';
import Head from 'next/head';

export default function MarketPlace() {
  const { contract: marketplace, isLoading: loadingMarketplace } = useContract(
    MUMBAI_MARKETPLACE_ADDRESS,
    'marketplace-v3'
  );

  const { data: directListings, isLoading: loadingDirectListings } = useDirectListings(
    marketplace,
    {
      tokenContract: MUMBAI_DIGITIZE_ETH_ADDRESS,
    }
  );

  return (
    <>
      <Head>
        <title> Marketplace | Digitize.eth</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <Navbar />
      <div className="container" style={{
        marginTop: 100
      }}>
        <h4>Marketplace</h4>
        <div>
          {!!directListings ? (
            directListings
              ?.filter((listing) => listing.status === 4)
              ?.map((listing, index) => (
                <div className='card' key={index}>
                  <PackNFTCard
                    contractAddress={listing.assetContractAddress}
                    tokenId={listing.tokenId}
                  />
                </div>
              ))
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </div>
    </>
  );
}
