import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Digitize.eth</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<div class="container-fluid" style={{
					maxWidth: 1100
				}}>
					<a class="navbar-brand" style={{
						fontFamily: "monospace",
						fontWeight: "bold"
					}} href="#">Digitize</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a class="nav-link" href="#">How it works</a>
							</li>
						</ul>
						<form class="d-flex">
							<button class="btn btn-light" type="submit">Connect Wallet</button>
						</form>
					</div>
				</div>
			</nav>
			<div className='container'>
				<div className="row" style={{
					display: "flex",
					justifyContent: "center",
					alignItems: "center"
				}}>
					<div className='col-sm'>
						<h1 style={{
							fontSize: 60,
							fontWeight: "bold"
						}}>Digitize your physical collectibles into NFTs</h1>
					</div>
					<div className='col-sm'>
						<img src="https://i.psacard.com/psacard/images/v4/services/tradingcard/grading-value.jpg" />
					</div>
				</div>
			</div>
		</>
	)
}
