import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React from "react";
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title> Home | Digitize.eth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar />
      <div
        className={`${styles.center} container`}
        style={{
          marginTop: 100,
        }}
      >
        <div
          className="row"
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <div className="col-sm">
            <h1
              style={{
                fontSize: 70,
                fontWeight: "bold",
              }}
            >
              Digitize your physical collectibles into NFTs
            </h1>
          </div>
          <div className="col-sm">
            <img
              className="landingImage"
              style={{
                width: "100%",
                maxWidth: 400,
                padding: 30,
              }}
              src={"/image1.png"}
            />
          </div>
        </div>
        <div
          style={{
            marginTop: 100,
          }}
        >
          <div className="row">
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/psacard/images/resources/gradingstandards/1952-topps-mickey-mantel-psa-pr-1.png"
                />
              </div>

              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-mkr-big.png"
                />
              </div>

              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-oc-big.png"
                />
              </div>
              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-pd-big.png"
                />
              </div>

              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-of-big.png"
                />
              </div>

              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
            <div className={`card col-sm`}>
              <div className="row">
                <img
                  width={150}
                  src="https://i.psacard.com/cardfacts/1999-nintendo-pokemon-game-4-charizard-holo-1st-edition-91294.jpg?h=1000"
                />
              </div>
              <div className="cardRow">
                <h3>[413928878] Kobe Bryant</h3>
                Cost: 1.0 MATIC
                <p>Creator: 0x1fa6756aC6D9104B0837Dee0d736a51f664A6a66</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
