import Head from 'next/head'
import Image from 'next/image'
import { Inconsolata } from 'next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Digitize your physical collectibles into NFTs | Digitize.eth</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav class="navbar navbar-expand-lg navbar-dark" style={{
				backgroundColor: "black"
			}}>
				<div class="container-fluid" style={{
					maxWidth: 1100
				}}>
					<a class="navbar-brand" style={{
						fontWeight: "bold"
					}} href="#">Digitize.eth</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a class="nav-link" style={{ fontWeight: "bold" }} href="#">Start Trading</a>
							</li>
						</ul>
						<form class="d-flex">
							<button style={{
								width: 200
							}} class="btn btn-outline-light" type="submit">Connect Wallet</button>
						</form>
					</div>
				</div>
			</nav>
			<div className='container'>
				<div className="row" style={{
					display: "flex",
					justifyContent: "center",
					alignItems: "center"
				}}>
					<div className='col-sm'>
						<h1 style={{
							fontSize: 60,
							fontWeight: "bold"
						}}>Digitize your physical collectibles into NFTs</h1>
					</div>
					<div className='col-sm'>
						<img src="https://i.psacard.com/psacard/images/v4/services/tradingcard/grading-value.jpg" />
					</div>
				</div>
				<div style={{
					marginTop: 100
				}}>
					<div className='row'>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/1952-topps-mickey-mantel-psa-pr-1.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-mkr-big.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-oc-big.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
					</div>
					<div className='row'>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-pd-big.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-of-big.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
						<div style={{ border: "2px solid black", borderRadius: 6, padding: 30, margin: 20 }} className='col-sm'>
							<div className='row'>
								<img width={200} src="https://i.psacard.com/psacard/images/resources/gradingstandards/1952-topps-mickey-mantel-psa-pr-1.png" />
							</div>
							<div className='row'>
								<div className='col-sm-9'>
									<h3>Card content</h3>
									<p>More card content</p>
								</div>
								<div className='col-sm-3'>
									Info
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</>
	)
}
