import React from 'react'
import { ConnectWallet } from '@thirdweb-dev/react';
import { useAddress } from "@thirdweb-dev/react";
import Head from 'next/head';

export default function index() {
	const address = useAddress();
	return (
    <>
      <Head>
        <title>Dashboard | Digitize.eth</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className='navbar navbar-expand-lg navbar-dark fixed-top'>
        <div
          className='container-fluid'
          style={{
            maxWidth: 1150,
            paddingTop: 10,
            paddingBottom: 10,
          }}
        >
          <a
            className='navbar-brand'
            style={{
              fontWeight: 'bold',
              alignItems: 'center',
            }}
            href='/'
          >
            <img width={46} src={'/logo.png'} />
            Digitize.eth
          </a>
          <button
            className='navbar-toggler'
            type='button'
            data-bs-toggle='collapse'
            data-bs-target='#navbarSupportedContent'
            aria-controls='navbarSupportedContent'
            aria-expanded='false'
            aria-label='Toggle navigation'
          >
            <span className='navbar-toggler-icon'></span>
          </button>
          <div className='collapse navbar-collapse' id='navbarSupportedContent'>
            <ul className='navbar-nav me-auto mb-2 mb-lg-0'>
              <li className='nav-item'>
                <a className='nav-link' style={{ fontWeight: 'bold' }} href='/dashboard'>
                  Dashboard
                </a>
              </li>
              <li className='nav-item'>
                <a className='nav-link' style={{ fontWeight: 'bold' }} href='/guide'>
                  How it Works
                </a>
              </li>
              <li className='nav-item'>
                <a
                  className='nav-link'
                  style={{ fontWeight: 'bold' }}
                  href='/marketplace'
                >
                  Marketplace
                </a>
              </li>
            </ul>
            <form className='d-flex'>
              <ConnectWallet />
            </form>
          </div>
        </div>
      </nav>
      <div
        className='container'
        style={{
          marginTop: 100,
        }}
      >
        <h1
          style={{
            fontSize: 30,
            fontWeight: 'bold',
            marginLeft: 20,
          }}
        >
          Welcome Back
        </h1>
        <div
          className='row'
          style={{
            borderBottom: '1px solid grey',
            padding: 20,
          }}
        >
          <p>
            {address ? (
              <div
                style={{
                  backgroundColor: '#111111',
                  padding: 20,
                  borderRadius: 12,
                }}
              >
                {address.substring(0, 6).concat('...')}
                {address.substring(address.length - 5, address.length - 1)}
              </div>
            ) : (
              'Not signed in'
            )}
          </p>
        </div>
        <div
          className='row'
          style={{
            padding: 20,
          }}
        >
          <div
            style={{
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
            }}
          >
            <h4>Your Items</h4>{' '}
            <button
              style={{
                marginLeft: 20,
              }}
              className='btn btn-outline-primary'
            >
              Mint New
            </button>
          </div>
          <div>
            <div className='row'>
              <div className={`card col-sm`}>
                <div className='row'>
                  <img
                    width={150}
                    src='https://i.psacard.com/psacard/images/resources/gradingstandards/1952-topps-mickey-mantel-psa-pr-1.png'
                  />
                </div>
                <div
                  className='row'
                  style={{
                    padding: 20,
                    paddingTop: 0,
                  }}
                >
                  <div className='col-sm-9'>
                    <h3>Card content</h3>
                  </div>
                  <div className='col-sm-3'>Info</div>
                </div>
              </div>
              <div className={`card col-sm`}>
                <div className='row'>
                  <img
                    width={150}
                    src='https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-mkr-big.png'
                  />
                </div>
                <div
                  className='row'
                  style={{
                    padding: 20,
                    paddingTop: 0,
                  }}
                >
                  <div className='col-sm-9'>
                    <h3>Card content</h3>
                  </div>
                  <div className='col-sm-3'>Info</div>
                </div>
              </div>
              <div className={`card col-sm`}>
                <div className='row'>
                  <img
                    width={150}
                    src='https://i.psacard.com/psacard/images/resources/gradingstandards/grdstd-qualifier-oc-big.png'
                  />
                </div>
                <div
                  className='row'
                  style={{
                    padding: 20,
                    paddingTop: 0,
                  }}
                >
                  <div className='col-sm-9'>
                    <h3>Card content</h3>
                  </div>
                  <div className='col-sm-3'>Info</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
